# Generated by Django 3.0.8 on 2021-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationroutes',
            name='map_src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='longroutes',
            name='map_src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='longrunroutes',
            name='map_src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mediumroutes',
            name='map_src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shortroutes',
            name='map_src',
            field=models.TextField(),
        ),
    ]
